/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import java.nio.file.Path;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.KuraIOException;
import org.eclipse.kura.net.IP4Address;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetworkPair;
import org.eclipse.kura.net.firewall.RuleType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Test class for AbstractLinuxFirewall ICMP rule detection functionality.
 * This feature verifies that ICMP rules in additional rules prevent allowIcmp
 * from being set.
 */
public class AbstractLinuxFirewallTest {
    @TempDir
    Path directory;

    private TestableAbstractLinuxFirewall firewall;
    private IptablesConfig mockIptablesConfig;
    private Set<String> filterRules;
    private Set<String> natRules;
    private Set<String> mangleRules;
    private boolean initialIcmpSetting;

    @BeforeEach
    public void setUp() {
        this.mockIptablesConfig = mock(IptablesConfig.class);
        this.firewall = new TestableAbstractLinuxFirewall();
        this.firewall.iptables = this.mockIptablesConfig;
        this.filterRules = new HashSet<>();
        this.natRules = new HashSet<>();
        this.mangleRules = new HashSet<>();
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(booleans = {false, true})
    public void setAdditionalRulesWithIcmpRulesInFilter(boolean allowIcmp) throws KuraException {
        this.firewall.allowIcmp = allowIcmp;
        this.initialIcmpSetting = allowIcmp;
        givenAdditionalRulesWithIcmpInFilter();

        whenSettingAdditionalRules();

        thenExplicitIcmpSettingIsPreserved();
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(booleans = {false, true})
    public void setAdditionalRulesWithIcmpRulesInNat(boolean allowIcmp) throws KuraException {
        this.firewall.allowIcmp = allowIcmp;
        this.initialIcmpSetting = allowIcmp;
        givenAdditionalRulesWithIcmpInNat();

        whenSettingAdditionalRules();

        thenExplicitIcmpSettingIsPreserved();
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(booleans = {false, true})
    public void setAdditionalRulesWithIcmpRulesInMangle(boolean allowIcmp) throws KuraException {
        this.firewall.allowIcmp = allowIcmp;
        this.initialIcmpSetting = allowIcmp;
        givenAdditionalRulesWithIcmpInMangle();

        whenSettingAdditionalRules();

        thenExplicitIcmpSettingIsPreserved();
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(booleans = {false, true})
    public void setAdditionalRulesWithoutIcmpRules(boolean allowIcmp) throws KuraException {
        this.firewall.allowIcmp = allowIcmp;
        this.initialIcmpSetting = allowIcmp;
        givenAdditionalRulesWithoutIcmp();

        whenSettingAdditionalRules();

        thenExplicitIcmpSettingIsPreserved();
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(booleans = {false, true})
    public void setAdditionalRulesWithEmptyRules(boolean allowIcmp) throws KuraException {
        this.firewall.allowIcmp = allowIcmp;
        this.initialIcmpSetting = allowIcmp;
        givenEmptyAdditionalRules();

        whenSettingAdditionalRules();

        thenExplicitIcmpSettingIsPreserved();
    }



    @Test
    public void blockingAllPortsClearsLocalPortForwardNatAndAutoNatRules() throws KuraException, UnknownHostException {
        givenExistingLocalPortForwardAndNatRules();
        givenExistingAutoNatRule();

        whenBlockingAllPorts();

        thenAllRuleSetsAreEmpty();
    }

    @Test
    public void legacyUnblockAllPortsResetsRules() throws Exception {
        givenExistingLocalPortForwardAndNatRules();
        givenExistingAutoNatRule();
        this.firewall.unblockAllPorts();
        thenAllRuleSetsAreEmpty();
    }

    private void thenExplicitIcmpSettingIsPreserved() {
        verify(this.mockIptablesConfig).setAllowIcmp(this.initialIcmpSetting);
        verify(this.mockIptablesConfig).setAdditionalFilterRules(this.filterRules);
        verify(this.mockIptablesConfig).setAdditionalNatRules(this.natRules);
        verify(this.mockIptablesConfig).setAdditionalMangleRules(this.mangleRules);
    }

    // Given methods

    private void givenExistingLocalPortForwardAndNatRules() throws KuraException, UnknownHostException {
        try {
            this.firewall.addLocalRules(Arrays.asList(newLocalRule(5400)));
        } catch (KuraIOException e) {
            throw new AssertionError("Unexpected firewall IO failure", e);
        }
        try {
            this.firewall.addPortForwardRules(Arrays.asList(newPortForwardRule(4040)));
        } catch (KuraIOException e) {
            throw new AssertionError("Unexpected firewall IO failure", e);
        }
        try {
            this.firewall.addNatRules(Arrays.asList(newNatRule("eth0", "eth1")));
        } catch (KuraIOException e) {
            throw new AssertionError("Unexpected firewall IO failure", e);
        }
    }

    private void givenExistingAutoNatRule() throws KuraException {
        try {
            this.firewall.addAutoNatRules(Arrays.asList(newNatRule("eth4", "eth5")));
        } catch (KuraIOException e) {
            throw new AssertionError("Unexpected firewall IO failure", e);
        }
    }

    private LocalRule newLocalRule(int port) throws UnknownHostException {
        return new LocalRule(
                port,
                "tcp",
                new NetworkPair<>((IP4Address) IPAddress.parseHostAddress("0.0.0.0"), (short) 0),
                "eth0",
                null,
                "00:11:22:33:44:55:66",
                "10100:10200");
    }

    private PortForwardRule newPortForwardRule(int inPort) {
        return new PortForwardRule()
                .inboundIface("eth0")
                .outboundIface("eth1")
                .address("172.16.0.1")
                .protocol("tcp")
                .inPort(inPort)
                .outPort(4050)
                .masquerade(true)
                .permittedNetwork("172.16.0.100")
                .permittedNetworkMask(32);
    }

    private NATRule newNatRule(String sourceInterface, String destinationInterface) {
        return new NATRule(sourceInterface, destinationInterface, null, null, null, true, RuleType.GENERIC);
    }

    private void givenAdditionalRulesWithIcmpInFilter() {
        this.filterRules.add("-A input-kura -p icmp --icmp-type 8 -j DROP");
        this.filterRules.add("-A input-kura -p tcp --dport 80 -j ACCEPT");
    }

    private void givenAdditionalRulesWithIcmpInNat() {
        this.natRules.add("-A prerouting-kura --protocol ipv6-icmp --icmpv6-type 129 -j DROP");
        this.natRules.add("-A prerouting-kura -p tcp --dport 443 -j ACCEPT");
    }

    private void givenAdditionalRulesWithIcmpInMangle() {
        this.mangleRules.add(
                "-A prerouting-kura -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j DROP");
        this.mangleRules.add("-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP");
    }

    private void givenAdditionalRulesWithoutIcmp() {
        this.filterRules.add("-A input-kura -p tcp --dport 80 -j ACCEPT");
        this.natRules.add("-A prerouting-kura -p tcp --dport 443 -j ACCEPT");
        this.mangleRules.add("-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP");
    }

    private void givenEmptyAdditionalRules() {
        // filterRules, natRules, and mangleRules are already empty
    }

    // When methods

    private void whenSettingAdditionalRules() throws KuraException {
        this.firewall.setAdditionalRules(this.filterRules, this.natRules, this.mangleRules);
    }



    private void whenBlockingAllPorts() throws KuraException {
        try {
            this.firewall.blockAllPorts();
        } catch (KuraIOException e) {
            throw new AssertionError("Unexpected firewall IO failure", e);
        }
    }



    // Then methods







    private void thenAllRuleSetsAreEmpty() {
        assertTrue(this.firewall.getLocalRules().isEmpty());
        assertTrue(this.firewall.getPortForwardRules().isEmpty());
        assertTrue(this.firewall.getNatRules().isEmpty());
        assertTrue(this.firewall.getAutoNatRules().isEmpty());
    }



    /**
     * Testable implementation of AbstractLinuxFirewall for testing purposes.
     */
    private class TestableAbstractLinuxFirewall extends AbstractLinuxFirewall {

        public TestableAbstractLinuxFirewall() {
            super();
            this.allowIcmp = false;
        }

        @Override
        protected IPAddress getDefaultAddress() throws UnknownHostException {
            return IPAddress.parseHostAddress("0.0.0.0");
        }

        @Override
        protected String getIpForwardFileName() {
            return directory.resolve("ip_forward").toString();
        }
    }
}
