/*******************************************************************************
 * Copyright (c) 2020, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import java.nio.file.Path;
import java.util.Set;
import org.junit.jupiter.api.io.TempDir;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;

public class FirewallTestUtils {

    @TempDir
    protected Path directory;

    // Exercise the real serializer with per-test paths, never /etc or shared /tmp files.
    protected class IsolatedIptablesConfig extends IptablesConfig {
        IsolatedIptablesConfig() { super(); }
        IsolatedIptablesConfig(CommandExecutorService executor) { super(executor); }
        IsolatedIptablesConfig(Set<LocalRule> local, Set<PortForwardRule> forward,
                Set<NATRule> autoNat, Set<NATRule> nat, boolean icmp, CommandExecutorService executor) {
            super(local, forward, autoNat, nat, icmp, executor);
        }
        @Override public String getFirewallConfigFileName() {
            return directory.resolve("iptables.conf").toString();
        }
        @Override public String getFirewallConfigTmpFileName() {
            return directory.resolve("iptables.tmp").toString();
        }
    }


    protected CommandExecutorService executorServiceMock;
    protected final CommandStatus successStatus =
            new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
    protected Command commandRestore;
    protected Command commandRestoreTmp;
    protected Command commandSave;
    protected Command commandSaveTmp;
    protected Command commandFlushInputFilter;
    protected Command commandFlushOutputFilter;
    protected Command commandFlushForwardFilter;
    protected Command commandFlushForwardPfFilter;
    protected Command commandFlushForwardIpfFilter;
    protected Command commandFlushInputNat;
    protected Command commandFlushOutputNat;
    protected Command commandFlushPreroutingNat;
    protected Command commandFlushPreroutingPfNat;
    protected Command commandFlushPostroutingNat;
    protected Command commandFlushPostroutingPfNat;
    protected Command commandFlushPostroutingIpfNat;
    protected Command commandFlushPreroutingMangle;
    protected Command commandFlushPostroutingMangle;
    protected Command commandFlushInputMangle;
    protected Command commandFlushOutputMangle;
    protected Command commandFlushForwardMangle;
    protected Command commandIcmpAccept1;
    protected Command commandIcmpAccept2;
    protected List<Command> commandApplyList;
    protected List<Command> testCommandList;

    protected void setUpMock() {
        executorServiceMock = mock(CommandExecutorService.class);
        when(executorServiceMock.execute(org.mockito.ArgumentMatchers.any(Command.class))).thenReturn(successStatus);
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig();
        commandRestore =
                new Command(new String[] {"iptables-restore", iptablesConfig.getFirewallConfigFileName()});
        commandRestore.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandRestore)).thenReturn(successStatus);
        commandRestoreTmp = new Command(
                new String[] {"iptables-restore", iptablesConfig.getFirewallConfigTmpFileName()});
        commandRestoreTmp.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandRestoreTmp)).thenReturn(successStatus);
        commandSave = new Command(new String[] {"iptables-save", ">", iptablesConfig.getFirewallConfigFileName()});
        commandSave.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandSave)).thenReturn(successStatus);
        commandSaveTmp =
                new Command(new String[] {"iptables-save", ">", iptablesConfig.getFirewallConfigTmpFileName()});
        commandSaveTmp.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandSaveTmp)).thenReturn(successStatus);
        commandFlushInputFilter = new Command(new String[] {"iptables", "-F", "input-kura", "-t", "filter"});
        commandFlushInputFilter.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushInputFilter)).thenReturn(successStatus);
        commandFlushOutputFilter = new Command(new String[] {"iptables", "-F", "output-kura", "-t", "filter"});
        commandFlushOutputFilter.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushOutputFilter)).thenReturn(successStatus);
        commandFlushForwardFilter = new Command(new String[] {"iptables", "-F", "forward-kura", "-t", "filter"});
        commandFlushForwardFilter.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushForwardFilter)).thenReturn(successStatus);
        commandFlushForwardPfFilter = new Command(new String[] {"iptables", "-F", "forward-kura-pf", "-t", "filter"});
        commandFlushForwardPfFilter.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushForwardPfFilter)).thenReturn(successStatus);
        commandFlushForwardIpfFilter = new Command(new String[] {"iptables", "-F", "forward-kura-ipf", "-t", "filter"});
        commandFlushForwardIpfFilter.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushForwardIpfFilter)).thenReturn(successStatus);
        commandFlushInputNat = new Command(new String[] {"iptables", "-F", "input-kura", "-t", "nat"});
        commandFlushInputNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushInputNat)).thenReturn(successStatus);
        commandFlushOutputNat = new Command(new String[] {"iptables", "-F", "output-kura", "-t", "nat"});
        commandFlushOutputNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushOutputNat)).thenReturn(successStatus);
        commandFlushPreroutingNat = new Command(new String[] {"iptables", "-F", "prerouting-kura", "-t", "nat"});
        commandFlushPreroutingNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPreroutingNat)).thenReturn(successStatus);
        commandFlushPreroutingPfNat = new Command(new String[] {"iptables", "-F", "prerouting-kura-pf", "-t", "nat"});
        commandFlushPreroutingPfNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPreroutingPfNat)).thenReturn(successStatus);
        commandFlushPostroutingNat = new Command(new String[] {"iptables", "-F", "postrouting-kura", "-t", "nat"});
        commandFlushPostroutingNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPostroutingNat)).thenReturn(successStatus);
        commandFlushPostroutingPfNat = new Command(new String[] {"iptables", "-F", "postrouting-kura-pf", "-t", "nat"});
        commandFlushPostroutingPfNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPostroutingPfNat)).thenReturn(successStatus);
        commandFlushPostroutingIpfNat =
                new Command(new String[] {"iptables", "-F", "postrouting-kura-ipf", "-t", "nat"});
        commandFlushPostroutingIpfNat.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPostroutingIpfNat)).thenReturn(successStatus);
        commandFlushPreroutingMangle = new Command(new String[] {"iptables", "-F", "prerouting-kura", "-t", "mangle"});
        commandFlushPreroutingMangle.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPreroutingMangle)).thenReturn(successStatus);
        commandFlushPostroutingMangle =
                new Command(new String[] {"iptables", "-F", "postrouting-kura", "-t", "mangle"});
        commandFlushPostroutingMangle.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushPostroutingMangle)).thenReturn(successStatus);
        commandFlushInputMangle = new Command(new String[] {"iptables", "-F", "input-kura", "-t", "mangle"});
        commandFlushInputMangle.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushInputMangle)).thenReturn(successStatus);
        commandFlushOutputMangle = new Command(new String[] {"iptables", "-F", "output-kura", "-t", "mangle"});
        commandFlushOutputMangle.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushOutputMangle)).thenReturn(successStatus);
        commandFlushForwardMangle = new Command(new String[] {"iptables", "-F", "forward-kura", "-t", "mangle"});
        commandFlushForwardMangle.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandFlushForwardMangle)).thenReturn(successStatus);
        commandIcmpAccept1 = new Command(
                "iptables -A input-kura -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT -t filter"
                        .split(" "));
        commandIcmpAccept1.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandIcmpAccept1)).thenReturn(successStatus);
        commandIcmpAccept2 = new Command(
                "iptables -A output-kura -p icmp -m icmp --icmp-type 0 -m state --state RELATED,ESTABLISHED -j ACCEPT -t filter"
                        .split(" "));
        commandIcmpAccept2.setExecuteInAShell(true);
        when(executorServiceMock.execute(commandIcmpAccept2)).thenReturn(successStatus);
        commandApplyList = new ArrayList<>();
        commandApplyList.add(new Command("iptables -P INPUT DROP".split(" ")));
        commandApplyList.add(new Command("iptables -P FORWARD DROP".split(" ")));
        commandApplyList.add(new Command("iptables -N input-kura -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -N output-kura -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -N forward-kura -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -N forward-kura-pf -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -N forward-kura-ipf -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -N input-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N output-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N prerouting-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N prerouting-kura-pf -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N postrouting-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N postrouting-kura-pf -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N postrouting-kura-ipf -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -N input-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -N output-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -N prerouting-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -N postrouting-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -C INPUT -j input-kura -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -C OUTPUT -j output-kura -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -C FORWARD -j forward-kura -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -C forward-kura -j forward-kura-pf -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -C forward-kura -j forward-kura-ipf -t filter".split(" ")));
        commandApplyList.add(new Command("iptables -C INPUT -j input-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C OUTPUT -j output-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C PREROUTING -j prerouting-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C prerouting-kura -j prerouting-kura-pf -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C POSTROUTING -j postrouting-kura -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C postrouting-kura -j postrouting-kura-pf -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C postrouting-kura -j postrouting-kura-ipf -t nat".split(" ")));
        commandApplyList.add(new Command("iptables -C INPUT -j input-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -C OUTPUT -j output-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -C FORWARD -j forward-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -C PREROUTING -j prerouting-kura -t mangle".split(" ")));
        commandApplyList.add(new Command("iptables -C POSTROUTING -j postrouting-kura -t mangle".split(" ")));
        // This fork retains individual rule commands and chain-existence checks.
        commandApplyList.stream().forEach(c -> c.setExecuteInAShell(true));
        commandApplyList.stream()
                .forEach(c -> when(executorServiceMock.execute(c)).thenReturn(successStatus));

        testCommandList = new ArrayList<>();
        testCommandList.add(new Command("iptables -t nat -A postrouting-kura -o eth1 -j MASQUERADE".split(" ")));
        testCommandList.add(new Command(
                "iptables -A input-kura -p tcp -s 0.0.0.0/0 -i eth0 -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 --dport 5400 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A input-kura -p tcp -s 0.0.0.0/0 -i eth0 -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100 --dport 5400 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT".split(" ")));
        testCommandList.add(new Command("iptables -A forward-kura -i eth0 -o eth1 -j ACCEPT".split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-ipf -s 172.16.0.100/32 -d 172.16.0.1/32 -i eth0 -o eth1 -p tcp -m tcp -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-ipf -s 172.16.0.100/32 -d 172.16.0.1/32 -i eth0 -o eth1 -p tcp -m tcp -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10100 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -i eth0 -o eth1 -p tcp -m tcp -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -i eth0 -o eth1 -p tcp -m tcp -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10100 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-pf -s 172.16.0.1/32 -i eth1 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-ipf -s 172.16.0.1/32 -i eth1 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -t nat -A prerouting-kura-pf -s 172.16.0.100/32 -i eth0 -p tcp -m mac --mac-source 00:11:22:33:44:55:66 -m tcp --sport 10100:10200 --dport 3040 -j DNAT --to-destination 172.16.0.1:4050"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -t nat -A prerouting-kura-pf -s 172.16.0.100/32 -i eth0 -p tcp -m mac --mac-source 00:11:22:33:44:55:66 -m tcp --sport 10100:10100 --dport 3040 -j DNAT --to-destination 172.16.0.1:4050"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -t nat -A postrouting-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -o eth1 -p tcp -j MASQUERADE"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-ipf -s 172.16.0.1/32 -d 172.16.0.2/32 -i eth0 -o eth1 -p tcp -m tcp -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A forward-kura-ipf -s 172.16.0.2/32 -i eth1 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -t nat -A postrouting-kura-ipf -s 172.16.0.1/32 -d 172.16.0.2/32 -o eth1 -p tcp -j MASQUERADE"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A input-kura -p tcp -s 0.0.0.0/0 -i eth0 -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 --dport 5400 -j ACCEPT"
                        .split(" ")));
        testCommandList.add(new Command(
                "iptables -A input-kura -p tcp -s 0.0.0.0/0 -i eth0 -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100 --dport 5400 -j ACCEPT"
                        .split(" ")));
        testCommandList.stream().forEach(c -> c.setExecuteInAShell(true));
        testCommandList.stream()
                .forEach(c -> when(executorServiceMock.execute(c)).thenReturn(successStatus));
    }

    protected static final String IPTABLES_FILE_CONTENT = "*filter\n"
            + ":INPUT DROP [0:0]\n"
            + ":FORWARD DROP [0:0]\n"
            + ":OUTPUT ACCEPT [0:0]\n"
            + ":input-kura - [0:0]\n"
            + ":output-kura - [0:0]\n"
            + ":forward-kura - [0:0]\n"
            + ":forward-kura-pf - [0:0]\n"
            + ":forward-kura-ipf - [0:0]\n"
            + "-I INPUT -j input-kura\n"
            + "-I OUTPUT -j output-kura\n"
            + "-I FORWARD -j forward-kura\n"
            + "-I forward-kura -j forward-kura-pf\n"
            + "-I forward-kura -j forward-kura-ipf\n"
            + "-A input-kura -i lo -j ACCEPT\n"
            + "-A input-kura -m state --state RELATED,ESTABLISHED -j ACCEPT\n"
            + "-A input-kura -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT\n"
            + "-A output-kura -p icmp -m icmp --icmp-type 0 -m state --state RELATED,ESTABLISHED -j ACCEPT\n"
            + "-A input-kura -p tcp -s 0.0.0.0/0 -i eth0 --dport 22 -j ACCEPT\n"
            + "-A input-kura -p tcp -s 10.234.0.0/16 -i tun0 --dport 22 -j ACCEPT\n"
            + "-A input-kura -p tcp -s 0.0.0.0/0 -i eth0 --dport 443 -j ACCEPT\n"
            + "-A input-kura -p tcp -s 10.234.0.0/16 -i tun0 --dport 443 -j ACCEPT\n"
            + "-A input-kura -p tcp -s 0.0.0.0/0 -i eth0 --dport 4443 -j ACCEPT\n"
            + "-A input-kura -p tcp -s 10.234.0.0/16 -i tun0 --dport 4443 -j ACCEPT\n"
            + "-A input-kura -p udp -s 0.0.0.0/0 -i eth0 --dport 53 -j ACCEPT\n"
            + "-A input-kura -p udp -s 0.0.0.0/0 -i wlan0 --dport 53 -j ACCEPT\n"
            + "-A input-kura -p udp -s 0.0.0.0/0 -i eth0 --dport 67 -j ACCEPT\n"
            + "-A input-kura -p udp -s 0.0.0.0/0 -i wlan0 --dport 67 -j ACCEPT\n"
            + "-A forward-kura-pf -s 0.0.0.0/0 -d 172.16.0.1/32 -i eth0 -o wlan0 -p tcp -m tcp -j ACCEPT\n"
            + "-A forward-kura-pf -s 172.16.0.1/32 -i wlan0 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT\n"
            + "-A forward-kura -i wlan0 -o eth0 -j ACCEPT\n"
            + "-A forward-kura -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT\n"
            + "-A forward-kura-ipf -s 0.0.0.0/0 -d 0.0.0.0/0 -i eth0 -o wlan0 -p tcp -m tcp -j ACCEPT\n"
            + "-A forward-kura-ipf -s 0.0.0.0/0 -i wlan0 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT\n"
            + "-A input-kura -j RETURN\n"
            + "-A output-kura -j RETURN\n"
            + "-A forward-kura -j RETURN\n"
            + "-A forward-kura-pf -j RETURN\n"
            + "-A forward-kura-ipf -j RETURN\n"
            + "COMMIT\n"
            + "*nat\n"
            + ":INPUT ACCEPT [0:0]\n"
            + ":OUTPUT ACCEPT [0:0]\n"
            + ":PREROUTING ACCEPT [0:0]\n"
            + ":POSTROUTING ACCEPT [0:0]\n"
            + ":prerouting-kura - [0:0]\n"
            + ":prerouting-kura-pf - [0:0]\n"
            + ":postrouting-kura - [0:0]\n"
            + ":postrouting-kura-pf - [0:0]\n"
            + ":postrouting-kura-ipf - [0:0]\n"
            + ":input-kura - [0:0]\n"
            + ":output-kura - [0:0]\n"
            + "-I PREROUTING -j prerouting-kura\n"
            + "-I prerouting-kura -j prerouting-kura-pf\n"
            + "-I POSTROUTING -j postrouting-kura\n"
            + "-I postrouting-kura -j postrouting-kura-pf\n"
            + "-I postrouting-kura -j postrouting-kura-ipf\n"
            + "-I INPUT -j input-kura\n"
            + "-I OUTPUT -j output-kura\n"
            + "-A prerouting-kura-pf -i eth0 -p tcp -m tcp --dport 2020 -j DNAT --to-destination 172.16.0.1:1010\n"
            + "-A postrouting-kura-pf -d 172.16.0.1/32 -o wlan0 -p tcp -j MASQUERADE\n"
            + "-A postrouting-kura -o eth0 -j MASQUERADE\n"
            + "-A postrouting-kura-ipf -s 0.0.0.0/0 -d 0.0.0.0/0 -o wlan0 -p tcp -j MASQUERADE\n"
            + "-A postrouting-kura -j RETURN\n"
            + "-A postrouting-kura-pf -j RETURN\n"
            + "-A postrouting-kura-ipf -j RETURN\n"
            + "-A prerouting-kura -j RETURN\n"
            + "-A prerouting-kura-pf -j RETURN\n"
            + "-A input-kura -j RETURN\n"
            + "-A output-kura -j RETURN\n"
            + "COMMIT\n"
            + "*mangle\n"
            + ":INPUT ACCEPT [0:0]\n"
            + ":OUTPUT ACCEPT [0:0]\n"
            + ":FORWARD ACCEPT [0:0]\n"
            + ":PREROUTING ACCEPT [0:0]\n"
            + ":POSTROUTING ACCEPT [0:0]\n"
            + ":prerouting-kura - [0:0]\n"
            + ":postrouting-kura - [0:0]\n"
            + ":input-kura - [0:0]\n"
            + ":output-kura - [0:0]\n"
            + ":forward-kura - [0:0]\n"
            + "-I PREROUTING -j prerouting-kura\n"
            + "-I POSTROUTING -j postrouting-kura\n"
            + "-I INPUT -j input-kura\n"
            + "-I OUTPUT -j output-kura\n"
            + "-I FORWARD -j forward-kura\n"
            + "-A postrouting-kura -j RETURN\n"
            + "-A prerouting-kura -j RETURN\n"
            + "-A input-kura -j RETURN\n"
            + "-A output-kura -j RETURN\n"
            + "-A forward-kura -j RETURN\n"
            + "COMMIT\n";
}
