/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Stream;
import org.eclipse.kura.KuraIOException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class IptablesConfigIPv6Test extends FirewallTestUtils {

    @BeforeEach
    public void setUp() {
        setUpMock();
    }

    // Test state variables
    private IptablesConfigIPv6 iptablesConfig;
    private Set<String> foundRules;
    private String[] icmpRules;
    private Exception occurredException;
    private boolean hasIcmpAcceptRules;
    private int criticalRulesWithoutSourceRestriction;
    private boolean allowIcmp;
    private String iptablesRestoreCommand;

    // Expected IPv6 ICMP rules from IptablesConfigIPv6.ALLOW_ICMP_IPV6
    private static final String[] EXPECTED_IPV6_ICMP_RULES = {
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 1 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 2 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 3/0 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 3/1 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 4/0 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 4/1 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 4/2 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 128 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 129 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 144 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 145 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 146 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 147 -j ACCEPT",
        // Multicast Listener Discovery
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 130 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 131 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 132 -j ACCEPT",
        // Critical Neighbor/Router Discovery - no source restriction for IPv6
        // connectivity
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 133 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 134 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 135 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 136 -j ACCEPT",
        "-A input-kura -s fe80::/10 -p ipv6-icmp -m ipv6-icmp --icmpv6-type 141 -j ACCEPT",
        "-A input-kura -s fe80::/10 -p ipv6-icmp -m ipv6-icmp --icmpv6-type 142 -j ACCEPT",
        "-A input-kura -s fe80::/10 -p ipv6-icmp -m ipv6-icmp --icmpv6-type 148 -j ACCEPT",
        "-A input-kura -s fe80::/10 -p ipv6-icmp -m ipv6-icmp --icmpv6-type 149 -j ACCEPT",
        // Multicast Router Discovery
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 151 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 152 -j ACCEPT",
        "-A input-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 153 -j ACCEPT",
        // Forward rules
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 1 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 2 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 3/0 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 3/1 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 4/0 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 4/1 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 4/2 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 144 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 145 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 146 -j ACCEPT",
        "-A forward-kura -p ipv6-icmp -m ipv6-icmp --icmpv6-type 147 -j ACCEPT"
    };

    // Critical ICMPv6 types that should not have source restrictions
    private static final String[] CRITICAL_ICMPV6_TYPES_WITHOUT_SOURCE = {
        "133", // Router Solicitation
        "134", // Router Advertisement
        "135", // Neighbor Solicitation
        "136" // Neighbor Advertisement
    };

    // Regex pattern to match iptables rules that have source restrictions
    private static final String SOURCE_RESTRICTION_REGEX = ".*-s\\s+[^\\s]+.*";

    @Test
    public void shouldSaveIPv6IcmpRulesWhenIcmpAllowed() {
        givenIptablesConfigWithIcmpAllowed(true);

        whenSaveKuraChainsIsCalled();

        thenIPv6IcmpRulesAreGenerated();
        thenCriticalIPv6IcmpRulesAreWithoutSourceRestrictions();
        thenNoExceptionOccurred();
    }

    @Test
    public void shouldNotSaveIPv6IcmpRulesWhenIcmpNotAllowed() {
        givenIptablesConfigWithIcmpAllowed(false);

        whenSaveKuraChainsIsCalled();

        thenNoIPv6IcmpAcceptRulesArePresent();
        thenNoExceptionOccurred();
    }

    @Test
    public void shouldGenerateCorrectIPv6ConfigFile() {
        givenDefaultIptablesConfig();

        whenGetConfigFilePathsAreCalled();

        thenFirewallConfigFileNameIs("/etc/sysconfig/ip6tables");
        thenFirewallConfigTmpFileNameIs("/tmp/ip6tables");
    }

    @Test
    public void shouldVerifyCriticalIPv6Types() {
        givenDefaultIptablesConfig();

        whenGetAllowIcmpIsCalled();

        thenCriticalIPv6TypesAreAllowedWithoutSourceRestrictions();
    }

    /**
     * Test specifically for the fix that removed source restrictions from critical
     * ICMPv6 types.
     * This test verifies that Router/Neighbor Discovery packets (types 133-136) are
     * allowed
     * from any source, which is essential for IPv6 connectivity.
     */
    @Test
    public void shouldAllowCriticalIPv6ICMPWithoutSourceRestrictions() {
        givenDefaultIptablesConfig();

        whenGetAllowIcmpIsCalled();

        thenRouterSolicitationIsAllowedWithoutSourceRestriction();
        thenRouterAdvertisementIsAllowedWithoutSourceRestriction();
        thenNeighborSolicitationIsAllowedWithoutSourceRestriction();
        thenNeighborAdvertisementIsAllowedWithoutSourceRestriction();
    }

    /**
     * Test to verify that the IPv6 firewall rules enable DNS resolution.
     * This tests the fix for the issue where overly restrictive source restrictions
     * on critical ICMPv6 types prevented IPv6 DNS resolution.
     */
    @Test
    public void shouldEnableIPv6DnsResolutionThroughUnrestrictedICMP() {
        givenDefaultIptablesConfig();

        whenGetAllowIcmpIsCalled();

        thenAllCriticalIPv6TypesAreAllowedWithoutSourceRestrictions();
        thenMulticastListenerDiscoveryIsSupported();
    }

    @Test
    public void shouldGetIp6TablesRestoreCommand() {
        givenDefaultIptablesConfig();

        whenIptablesRestoreCommandIsRetrieved();

        thenIptablesRestoreCommandIs("ip6tables-restore");
    }

    // Given methods
    private void givenIptablesConfigWithIcmpAllowed(boolean allowIcmp) {
        this.allowIcmp = allowIcmp;
        this.iptablesConfig = new IptablesConfigIPv6(
                new LinkedHashSet<>(),
                new LinkedHashSet<>(),
                new LinkedHashSet<>(),
                new LinkedHashSet<>(),
                allowIcmp,
                executorServiceMock) {
            @Override public String getFirewallConfigFileName() {
                return directory.resolve("ip6tables.conf").toString();
            }
            @Override public String getFirewallConfigTmpFileName() {
                return directory.resolve("ip6tables.tmp").toString();
            }
        };
    }

    private void givenDefaultIptablesConfig() {
        this.iptablesConfig = new IptablesConfigIPv6();
    }

    // When methods
    private void whenSaveKuraChainsIsCalled() {
        org.junit.jupiter.api.Assertions.assertDoesNotThrow(() -> this.iptablesConfig.saveKuraChains());
    }

    private void whenGetConfigFilePathsAreCalled() {
        // This method is used to test the file path getters
        // The actual calls happen in the then methods
    }

    private void whenGetAllowIcmpIsCalled() {
        try {
            this.icmpRules = this.iptablesConfig.getAllowIcmp();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenIptablesRestoreCommandIsRetrieved() {
        new IptablesConfigIPv6(executorServiceMock).restore(directory.resolve("restore-input").toString());
        org.mockito.ArgumentCaptor<org.eclipse.kura.executor.Command> command =
                org.mockito.ArgumentCaptor.forClass(org.eclipse.kura.executor.Command.class);
        org.mockito.Mockito.verify(executorServiceMock).execute(command.capture());
        this.iptablesRestoreCommand = command.getValue().getCommandLine()[0];
    }

    // Then methods
    private void thenIPv6IcmpRulesAreGenerated() {
        this.foundRules = org.junit.jupiter.api.Assertions.assertDoesNotThrow(() ->
                new HashSet<>(Files.readAllLines(Paths.get(this.iptablesConfig.getFirewallConfigFileName()))));
        assertTrue(this.foundRules.containsAll(java.util.Arrays.asList(EXPECTED_IPV6_ICMP_RULES)),
                "The real serialized config must contain every expected ICMPv6 rule");
    }

    private void thenCriticalIPv6IcmpRulesAreWithoutSourceRestrictions() {
        if (this.foundRules != null) {
            assertTrue(this.foundRules.stream()
                            .anyMatch(rule -> rule.contains("--icmpv6-type 133") && !rule.contains("-s")), "IPv6 ICMP rules should include neighbor discovery types without source restrictions");
            assertTrue(this.foundRules.stream()
                            .anyMatch(rule -> rule.contains("--icmpv6-type 134") && !rule.contains("-s")), "IPv6 ICMP rules should include router advertisement without source restrictions");
            assertTrue(this.foundRules.stream()
                            .anyMatch(rule -> rule.contains("--icmpv6-type 135") && !rule.contains("-s")), "IPv6 ICMP rules should include neighbor solicitation without source restrictions");
            assertTrue(this.foundRules.stream()
                            .anyMatch(rule -> rule.contains("--icmpv6-type 136") && !rule.contains("-s")), "IPv6 ICMP rules should include neighbor advertisement without source restrictions");
        }
        // Clean up
        try {
            File configFile = new File(this.iptablesConfig.getFirewallConfigTmpFileName());
            Files.deleteIfExists(configFile.toPath());
        } catch (IOException e) {
            // Ignore cleanup errors
        }
    }

    private void thenNoIPv6IcmpAcceptRulesArePresent() {
        java.util.List<String> lines = org.junit.jupiter.api.Assertions.assertDoesNotThrow(() ->
                Files.readAllLines(Paths.get(this.iptablesConfig.getFirewallConfigFileName())));
        assertFalse(lines.stream().anyMatch(line -> line.contains("-p ipv6-icmp") && line.contains("-j ACCEPT")),
                "No IPv6 ICMP ACCEPT rules should be present when ICMP is not allowed");
    }

    private void thenFirewallConfigFileNameIs(String expectedFileName) {
        assertEquals(expectedFileName, this.iptablesConfig.getFirewallConfigFileName());
    }

    private void thenFirewallConfigTmpFileNameIs(String expectedTmpFileName) {
        assertEquals(expectedTmpFileName, this.iptablesConfig.getFirewallConfigTmpFileName());
    }

    private void thenCriticalIPv6TypesAreAllowedWithoutSourceRestrictions() {
        for (String criticalType : CRITICAL_ICMPV6_TYPES_WITHOUT_SOURCE) {
            boolean foundWithoutSourceRestriction = false;
            for (String rule : this.icmpRules) {
                if (rule.contains("--icmpv6-type " + criticalType)
                        && rule.contains("-j ACCEPT")
                        && !rule.contains("-s ")) { // No source restriction
                    foundWithoutSourceRestriction = true;
                    break;
                }
            }
            assertTrue(foundWithoutSourceRestriction, "Critical ICMPv6 type " + criticalType + " should be allowed without source restrictions");
        }
    }

    private void thenRouterSolicitationIsAllowedWithoutSourceRestriction() {
        boolean routerSolicitationFound = false;
        for (String rule : this.icmpRules) {
            if (rule.contains("--icmpv6-type 133") && rule.contains("-j ACCEPT")) {
                assertFalse(rule.matches(SOURCE_RESTRICTION_REGEX), "Router Solicitation (133) should not have source restriction, but rule was: " + rule);
                routerSolicitationFound = true;
            }
        }
        assertTrue(routerSolicitationFound, "Router Solicitation (133) rule should exist");
    }

    private void thenRouterAdvertisementIsAllowedWithoutSourceRestriction() {
        boolean routerAdvertisementFound = false;
        for (String rule : this.icmpRules) {
            if (rule.contains("--icmpv6-type 134") && rule.contains("-j ACCEPT")) {
                assertFalse(rule.matches(SOURCE_RESTRICTION_REGEX), "Router Advertisement (134) should not have source restriction, but rule was: " + rule);
                routerAdvertisementFound = true;
            }
        }
        assertTrue(routerAdvertisementFound, "Router Advertisement (134) rule should exist");
    }

    private void thenNeighborSolicitationIsAllowedWithoutSourceRestriction() {
        boolean neighborSolicitationFound = false;
        for (String rule : this.icmpRules) {
            if (rule.contains("--icmpv6-type 135") && rule.contains("-j ACCEPT")) {
                assertFalse(rule.matches(SOURCE_RESTRICTION_REGEX), "Neighbor Solicitation (135) should not have source restriction, but rule was: " + rule);
                neighborSolicitationFound = true;
            }
        }
        assertTrue(neighborSolicitationFound, "Neighbor Solicitation (135) rule should exist");
    }

    private void thenNeighborAdvertisementIsAllowedWithoutSourceRestriction() {
        boolean neighborAdvertisementFound = false;
        for (String rule : this.icmpRules) {
            if (rule.contains("--icmpv6-type 136") && rule.contains("-j ACCEPT")) {
                assertFalse(rule.matches(SOURCE_RESTRICTION_REGEX), "Neighbor Advertisement (136) should not have source restriction, but rule was: " + rule);
                neighborAdvertisementFound = true;
            }
        }
        assertTrue(neighborAdvertisementFound, "Neighbor Advertisement (136) rule should exist");
    }

    private void thenAllCriticalIPv6TypesAreAllowedWithoutSourceRestrictions() {
        this.criticalRulesWithoutSourceRestriction = 0;

        for (String rule : this.icmpRules) {
            // Check for Router/Neighbor Discovery rules without source restrictions
            if ((rule.contains("--icmpv6-type 133")
                            || rule.contains("--icmpv6-type 134")
                            || rule.contains("--icmpv6-type 135")
                            || rule.contains("--icmpv6-type 136"))
                    && rule.contains("-j ACCEPT")
                    && !rule.matches(SOURCE_RESTRICTION_REGEX)) {
                this.criticalRulesWithoutSourceRestriction++;
            }
        }

        // All four critical types should be present without source restrictions
        assertTrue(this.criticalRulesWithoutSourceRestriction >= 4, "All critical ICMPv6 types (133-136) should be allowed without source restrictions to enable DNS resolution. Found: "
                        + this.criticalRulesWithoutSourceRestriction + " out of 4");
    }

    private void thenMulticastListenerDiscoveryIsSupported() {
        boolean hasMulticastSupport = false;
        for (String rule : this.icmpRules) {
            if ((rule.contains("--icmpv6-type 130")
                            || rule.contains("--icmpv6-type 131")
                            || rule.contains("--icmpv6-type 132"))
                    && rule.contains("-j ACCEPT")) {
                hasMulticastSupport = true;
                break;
            }
        }

        assertTrue(hasMulticastSupport, "Multicast Listener Discovery should be supported for complete IPv6 functionality");
    }

    private void thenNoExceptionOccurred() {
        String errorMessage = "No exception expected";
        if (Objects.nonNull(this.occurredException)) {
            StringWriter sw = new StringWriter();
            this.occurredException.printStackTrace(new PrintWriter(sw));

            errorMessage = String.format(
                    "No exception expected, \"%s\" found. Caused by: %s",
                    this.occurredException.getClass().getName(), sw.toString());
        }

        assertNull(this.occurredException, errorMessage);
    }



    private void thenIptablesRestoreCommandIs(String command) {
        assertEquals(command, this.iptablesRestoreCommand);
    }
}
