/*******************************************************************************
 * Copyright (c) 2020, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.atLeast;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.Stream;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.KuraIOException;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.net.IP4Address;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetworkPair;
import org.eclipse.kura.net.firewall.RuleType;
import org.junit.jupiter.api.Test;

public class IpTablesConfigTest extends FirewallTestUtils {

    @Test
    public void clearAllChainsTest() throws KuraException {
        setUpMock();
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.clearAllChains();

        verify(executorServiceMock, times(1)).execute(commandRestoreTmp);
    }

    @Test
    public void applyBlockPolicyTest() throws KuraException {
        setUpMock();
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.applyBlockPolicy();

        verify(executorServiceMock, times(1)).execute(commandRestoreTmp);
    }

    @Test
    public void clearAllKuraChainsTest() {
        setUpMock();
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.clearAllKuraChains();

        verify(executorServiceMock, times(1)).execute(commandFlushInputFilter);
        verify(executorServiceMock, times(1)).execute(commandFlushOutputFilter);
        verify(executorServiceMock, times(1)).execute(commandFlushForwardFilter);
        verify(executorServiceMock, times(1)).execute(commandFlushInputNat);
        verify(executorServiceMock, times(1)).execute(commandFlushOutputNat);
        verify(executorServiceMock, times(1)).execute(commandFlushPreroutingNat);
        verify(executorServiceMock, times(1)).execute(commandFlushPostroutingNat);
    }

    @Test
    public void saveTest() {
        setUpMock();
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.save();

        verify(executorServiceMock, times(1)).execute(commandSave);
    }

    @Test
    public void saveWithFilenameTest() {
        setUpMock();

        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.save(iptablesConfig.getFirewallConfigTmpFileName());

        verify(executorServiceMock, times(1)).execute(commandSaveTmp);
    }

    @Test
    public void restoreWithFilenameTest() {
        setUpMock();
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.restore(iptablesConfig.getFirewallConfigFileName());

        verify(executorServiceMock, times(1)).execute(commandRestore);
    }

    @Test
    public void saveKuraChainsTest() throws KuraException, IOException {
        setUpMock();
        Set<LocalRule> localRules = new LinkedHashSet<>();
        localRules.add(new LocalRule(
                5400,
                "tcp",
                new NetworkPair<>((IP4Address) IPAddress.parseHostAddress("0.0.0.0"), (short) 0),
                "eth0",
                null,
                "00:11:22:33:44:55:66",
                "10100:10200"));

        Set<PortForwardRule> portForwardRules = new LinkedHashSet<>();
        PortForwardRule portForwardRule = new PortForwardRule()
                .inboundIface("eth0")
                .outboundIface("eth1")
                .address("172.16.0.1")
                .addressMask(32)
                .protocol("tcp")
                .inPort(3040)
                .outPort(4050)
                .masquerade(true)
                .permittedNetwork("172.16.0.100")
                .permittedNetworkMask(32)
                .permittedMAC("00:11:22:33:44:55:66")
                .sourcePortRange("10100:10200");
        portForwardRules.add(portForwardRule);

        Set<NATRule> autoNatRules = new LinkedHashSet<>();
        autoNatRules.add(new NATRule("eth2", "eth3", true, RuleType.GENERIC));

        Set<NATRule> natRules = new LinkedHashSet<>();
        natRules.add(
                new NATRule("eth4", "eth5", "tcp", "172.16.0.1/24", "172.16.0.2/24", true, RuleType.IP_FORWARDING));

        IptablesConfig iptablesConfig =
                new IsolatedIptablesConfig(localRules, portForwardRules, autoNatRules, natRules, true, executorServiceMock);

        iptablesConfig.saveKuraChains();

        AtomicBoolean isLocalRulePresent = new AtomicBoolean(false);
        AtomicBoolean[] isPortForwardRulePresent = {
            new AtomicBoolean(false), new AtomicBoolean(false), new AtomicBoolean(false), new AtomicBoolean(false)
        };
        AtomicBoolean[] isAutoNatRulePresent = {
            new AtomicBoolean(false), new AtomicBoolean(false), new AtomicBoolean(false)
        };
        AtomicBoolean[] isNatRulePresent = {new AtomicBoolean(false), new AtomicBoolean(false), new AtomicBoolean(false)
        };
        try (Stream<String> lines = Files.lines(Paths.get(iptablesConfig.getFirewallConfigFileName()))) {
            lines.forEach(line -> {
                line = line.trim();
                switch (line) {
                    case "-A input-kura -p tcp -s 0.0.0.0/0 -i eth0 -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 --dport 5400 -j ACCEPT":
                        isLocalRulePresent.set(true);
                        break;
                    case "-A forward-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -i eth0 -o eth1 -p tcp -m tcp -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 -j ACCEPT":
                        isPortForwardRulePresent[0].set(true);
                        break;
                    case "-A forward-kura-pf -s 172.16.0.1/32 -i eth1 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT":
                        isPortForwardRulePresent[1].set(true);
                        break;
                    case "-A prerouting-kura-pf -s 172.16.0.100/32 -i eth0 -p tcp -m mac --mac-source 00:11:22:33:44:55:66 -m tcp --sport 10100:10200 --dport 3040 -j DNAT --to-destination 172.16.0.1:4050":
                        isPortForwardRulePresent[2].set(true);
                        break;
                    case "-A postrouting-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -o eth1 -p tcp -j MASQUERADE":
                        isPortForwardRulePresent[3].set(true);
                        break;
                    case "-A forward-kura -i eth2 -o eth3 -j ACCEPT":
                        isAutoNatRulePresent[0].set(true);
                        break;
                    case "-A forward-kura -i eth3 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT":
                        isAutoNatRulePresent[1].set(true);
                        break;
                    case "-A postrouting-kura -o eth3 -j MASQUERADE":
                        isAutoNatRulePresent[2].set(true);
                        break;
                    case "-A postrouting-kura-ipf -s 172.16.0.1/24 -d 172.16.0.2/24 -o eth5 -p tcp -j MASQUERADE":
                        isNatRulePresent[0].set(true);
                        break;
                    case "-A forward-kura-ipf -s 172.16.0.1/24 -d 172.16.0.2/24 -i eth4 -o eth5 -p tcp -m tcp -j ACCEPT":
                        isNatRulePresent[1].set(true);
                        break;
                    case "-A forward-kura-ipf -s 172.16.0.2/24 -i eth5 -o eth4 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT":
                        isNatRulePresent[2].set(true);
                        break;
                }
            });
        } catch (IOException e) {
            throw new KuraIOException(e, "save() :: failed to save rules on file");
        }
        assertTrue(isLocalRulePresent.get());
        assertTrue(isPortForwardRulePresent[0].get()
                && isPortForwardRulePresent[1].get()
                && isPortForwardRulePresent[2].get()
                && isPortForwardRulePresent[3].get());
        assertTrue(isAutoNatRulePresent[0].get() && isAutoNatRulePresent[1].get() && isAutoNatRulePresent[2].get());
        assertTrue(isNatRulePresent[0].get() && isNatRulePresent[1].get() && isNatRulePresent[2].get());

        File configFile = new File(iptablesConfig.getFirewallConfigTmpFileName());
        Files.deleteIfExists(configFile.toPath());
    }

    @Test
    public void applyRulesTest() {
        setUpMock();

        String[] mangleRulesArray = {
            "-A prerouting-kura -m conntrack --ctstate INVALID -j DROP",
            "-A prerouting-kura -p tcp ! --syn -m conntrack --ctstate NEW -j DROP",
            "-A prerouting-kura -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags FIN,RST FIN,RST -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags FIN,ACK FIN -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ACK,URG URG -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ACK,FIN FIN -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ACK,PSH PSH -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ALL ALL -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ALL NONE -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j DROP",
            "-A prerouting-kura -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP",
            "-A prerouting-kura -f -j DROP"
        };
        Set<String> mangleRules = new HashSet<String>(Arrays.asList(mangleRulesArray));

        // These rules are fake...
        String[] filterRulesArray = {"-A input-kura -p tcp -f -j DROP"};
        Set<String> filterRules = new HashSet<String>(Arrays.asList(filterRulesArray));

        // Also these ones...
        String[] natRulesArray = {"-A prerouting-kura -p tcp -f -j DROP"};
        Set<String> natRules = new HashSet<String>(Arrays.asList(natRulesArray));

        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(
                new LinkedHashSet<>(),
                new LinkedHashSet<>(),
                new LinkedHashSet<>(),
                new LinkedHashSet<>(),
                false,
                executorServiceMock);
        iptablesConfig.setAdditionalFilterRules(filterRules);
        iptablesConfig.setAdditionalNatRules(natRules);
        iptablesConfig.setAdditionalMangleRules(mangleRules);
        iptablesConfig.applyRules();

        for (Command c : commandApplyList) {
            System.out.println(c);
            verify(executorServiceMock, atLeast(1)).execute(c);
        }
    }

    @Test
    public void shouldRestoreConfig() throws KuraException, IOException {
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig() {
            @Override
            public String getFirewallConfigFileName() {
                return getFirewallConfigTmpFileName();
            }
        };

        BufferedWriter writer = new BufferedWriter(new FileWriter(iptablesConfig.getFirewallConfigTmpFileName()));
        writer.write(FirewallTestUtils.IPTABLES_FILE_CONTENT);
        writer.close();

        iptablesConfig.restore();

        assertEquals(10, iptablesConfig.localRules.size());
        assertEquals(1, iptablesConfig.portForwardRules.size());
        assertEquals(1, iptablesConfig.natRules.size());
        assertEquals(1, iptablesConfig.autoNatRules.size());

        File configFile = new File(iptablesConfig.getFirewallConfigTmpFileName());
        Files.deleteIfExists(configFile.toPath());
    }

    @Test
    public void testDefaultConstructor() {
        IptablesConfig config = new IsolatedIptablesConfig();

        assertNotNull(config.getLocalRules(), "Local rules should not be null");
        assertNotNull(config.getPortForwardRules(), "Port forward rules should not be null");
        assertNotNull(config.getAutoNatRules(), "Auto NAT rules should not be null");
        assertNotNull(config.getNatRules(), "NAT rules should not be null");
        assertNotNull(config.getAdditionalFilterRules(), "Additional filter rules should not be null");
        assertNotNull(config.getAdditionalNatRules(), "Additional NAT rules should not be null");
        assertNotNull(config.getAdditionalMangleRules(), "Additional mangle rules should not be null");
        assertTrue(config.allowIcmp(), "ICMP should be allowed by default");
    }

    @Test
    public void testConstructorWithExecutorService() {
        CommandExecutorService mockService = mock(CommandExecutorService.class);
        IptablesConfig config = new IsolatedIptablesConfig(mockService);

        assertNotNull(config.getLocalRules(), "Local rules should not be null");
        assertNotNull(config.getPortForwardRules(), "Port forward rules should not be null");
        assertNotNull(config.getAutoNatRules(), "Auto NAT rules should not be null");
        assertNotNull(config.getNatRules(), "NAT rules should not be null");
        assertTrue(config.allowIcmp(), "ICMP should be allowed by default");
    }

    @Test
    public void testFullConstructor() {
        Set<LocalRule> localRules = new LinkedHashSet<>();
        Set<PortForwardRule> portForwardRules = new LinkedHashSet<>();
        Set<NATRule> autoNatRules = new LinkedHashSet<>();
        Set<NATRule> natRules = new LinkedHashSet<>();
        CommandExecutorService mockService = mock(CommandExecutorService.class);
        boolean allowIcmp = false;

        IptablesConfig config =
                new IsolatedIptablesConfig(localRules, portForwardRules, autoNatRules, natRules, allowIcmp, mockService);

        assertSame(localRules, config.getLocalRules(), "Local rules should be the same instance");
        assertSame(portForwardRules, config.getPortForwardRules(), "Port forward rules should be the same instance");
        assertSame(autoNatRules, config.getAutoNatRules(), "Auto NAT rules should be the same instance");
        assertSame(natRules, config.getNatRules(), "NAT rules should be the same instance");
        assertFalse(config.allowIcmp(), "ICMP should be disabled");
        assertNotNull(config.getAdditionalFilterRules(), "Additional filter rules should be initialized");
        assertNotNull(config.getAdditionalNatRules(), "Additional NAT rules should be initialized");
        assertNotNull(config.getAdditionalMangleRules(), "Additional mangle rules should be initialized");
    }

    @Test
    public void testGetters() {
        IptablesConfig config = new IsolatedIptablesConfig();

        assertNotNull(config.getFirewallConfigFileName(), "getFirewallConfigFileName should not return null");
        assertNotNull(config.getFirewallConfigTmpFileName(), "getFirewallConfigTmpFileName should not return null");
        assertTrue(config.getFirewallConfigFileName().contains("iptables"), "getFirewallConfigFileName should contain iptables");
        assertTrue(config.getFirewallConfigTmpFileName().contains("tmp"), "getFirewallConfigTmpFileName should contain tmp");
    }

    @Test
    public void testSettersAndGetters() {
        IptablesConfig config = new IsolatedIptablesConfig();

        // Test local rules
        Set<LocalRule> newLocalRules = new LinkedHashSet<>();
        config.setLocalRules(newLocalRules);
        assertSame(newLocalRules, config.getLocalRules(), "Local rules should be updated");

        // Test port forward rules
        Set<PortForwardRule> newPortForwardRules = new LinkedHashSet<>();
        config.setPortForwardRules(newPortForwardRules);
        assertSame(newPortForwardRules, config.getPortForwardRules(), "Port forward rules should be updated");

        // Test auto NAT rules
        Set<NATRule> newAutoNatRules = new LinkedHashSet<>();
        config.setAutoNatRules(newAutoNatRules);
        assertSame(newAutoNatRules, config.getAutoNatRules(), "Auto NAT rules should be updated");

        // Test NAT rules
        Set<NATRule> newNatRules = new LinkedHashSet<>();
        config.setNatRules(newNatRules);
        assertSame(newNatRules, config.getNatRules(), "NAT rules should be updated");

        // Test additional filter rules
        Set<String> newFilterRules = new LinkedHashSet<>();
        newFilterRules.add("-A input-kura -p tcp --dport 8080 -j ACCEPT");
        config.setAdditionalFilterRules(newFilterRules);
        assertSame(newFilterRules, config.getAdditionalFilterRules(), "Additional filter rules should be updated");

        // Test additional NAT rules
        Set<String> newNatRulesSet = new LinkedHashSet<>();
        newNatRulesSet.add("-A postrouting-kura -o eth1 -j MASQUERADE");
        config.setAdditionalNatRules(newNatRulesSet);
        assertSame(newNatRulesSet, config.getAdditionalNatRules(), "Additional NAT rules should be updated");

        // Test additional mangle rules
        Set<String> newMangleRules = new LinkedHashSet<>();
        newMangleRules.add("-A prerouting-kura -p tcp --dport 80 -j MARK --set-mark 1");
        config.setAdditionalMangleRules(newMangleRules);
        assertSame(newMangleRules, config.getAdditionalMangleRules(), "Additional mangle rules should be updated");

        // Test ICMP settings
        config.setAllowIcmp(false);
        assertFalse(config.allowIcmp(), "ICMP should be disabled");

        config.setAllowIcmp(true);
        assertTrue(config.allowIcmp(), "ICMP should be enabled");
    }

    @Test
    public void testIcmpArrayMethods() {
        IptablesConfig config = new IsolatedIptablesConfig();

        String[] allowIcmp = config.getAllowIcmp();
        assertNotNull(allowIcmp, "getAllowIcmp should not return null");
        assertTrue(allowIcmp.length > 0, "getAllowIcmp should return non-empty array");

        String[] notAllowIcmp = config.getNotAllowIcmp();
        assertNotNull(notAllowIcmp, "getNotAllowIcmp should not return null");
        // Local IPv4 policy retains explicit echo request/reply DROP rules.
        assertEquals(2, notAllowIcmp.length, "This fork keeps explicit IPv4 ICMP DROP rules");
    }

    @Test
    public void testClearAllChainsIOException() throws KuraException {
        org.junit.jupiter.api.Assertions.assertThrows(KuraIOException.class, () -> {
        // Create a config that will cause an IOException when writing to file
        IptablesConfig config = new IsolatedIptablesConfig(mock(CommandExecutorService.class)) {
            @Override
            public String getFirewallConfigTmpFileName() {
                return directory.resolve("missing/iptables.tmp").toString();
            }
        };

        config.clearAllChains();
            });
    }

    @Test
    public void testApplyBlockPolicyIOException() throws KuraException {
        org.junit.jupiter.api.Assertions.assertThrows(KuraIOException.class, () -> {
        setUpMock();
        // Create a config that will cause an IOException when writing to file
        IptablesConfig config = new IsolatedIptablesConfig(executorServiceMock) {
            @Override
            public String getFirewallConfigTmpFileName() {
                return directory.resolve("missing/iptables.tmp").toString();
            }
        };

        config.applyBlockPolicy();
            });
    }

    @Test
    public void testClearAllKuraChainsWithNullExecutorService() {
        IptablesConfig config = new IsolatedIptablesConfig(); // No executor service

        // Should not throw an exception when executor service is null
        boolean methodCompleted = false;
        try {
            config.clearAllKuraChains();
            methodCompleted = true;
        } catch (Exception e) {
            methodCompleted = false;
        }

        // Verify that the method completed successfully without exceptions
        assertTrue(methodCompleted, "clearAllKuraChains() should complete successfully when executor service is null");

        // Additional assertion: verify that the config object is still in a valid state
        assertNotNull(config, "Config object should remain valid after clearAllKuraChains call");
    }

    @Test
    public void testSaveWithNullExecutorService() {
        org.junit.jupiter.api.Assertions.assertThrows(IllegalArgumentException.class, () -> {
        IptablesConfig config = new IsolatedIptablesConfig(); // No executor service
        config.save();
            });
    }

    @Test
    public void testRestoreWithNullExecutorService() {
        org.junit.jupiter.api.Assertions.assertThrows(IllegalArgumentException.class, () -> {
        IptablesConfig config = new IsolatedIptablesConfig(); // No executor service
        config.restore("test-file");
            });
    }

    @Test
    public void testSaveKuraChainsWithEmptyRules() throws KuraException, IOException {
        setUpMock();
        IptablesConfig config = new IsolatedIptablesConfig(executorServiceMock);

        // All rule sets are empty by default
        config.saveKuraChains();

        // Verify the temporary file was created
        File tempFile = new File(config.getFirewallConfigFileName());
        assertTrue(tempFile.isFile());
        {
            // Verify file content contains expected sections even with empty rules
            try (Stream<String> lines = Files.lines(tempFile.toPath())) {
                String content = String.join("\n", lines.toList());
                assertTrue(content.contains("*filter"), "File should contain *filter section");
                assertTrue(content.contains("*nat"), "File should contain *nat section");
                assertTrue(content.contains("COMMIT"), "File should contain COMMIT statements");
                assertTrue(content.contains("input-kura"), "File should contain input-kura chain");
            }

            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testRestoreWithNonExistentFile() throws KuraException {
        IptablesConfig config = new IsolatedIptablesConfig() {
            @Override
            public String getFirewallConfigFileName() {
                return directory.resolve("missing.conf").toString();
            }
        };

        // Should return immediately without error if file doesn't exist
        config.restore();

        // Verify rules remain empty
        assertTrue(config.getLocalRules().isEmpty(), "Local rules should be empty");
        assertTrue(config.getPortForwardRules().isEmpty(), "Port forward rules should be empty");
        assertTrue(config.getNatRules().isEmpty(), "NAT rules should be empty");
        assertTrue(config.getAutoNatRules().isEmpty(), "Auto NAT rules should be empty");
    }

    @Test
    public void testApplyRulesWithFailedCommands() {
        CommandExecutorService mockService = mock(CommandExecutorService.class);
        CommandStatus failedStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));
        when(mockService.execute(any(Command.class))).thenReturn(failedStatus);

        IptablesConfig config = new IsolatedIptablesConfig(mockService);

        // Should not throw exception even if commands fail
        config.applyRules();

        // Verify that execute was called multiple times (for various commands)
        verify(mockService, atLeast(10)).execute(any(Command.class));
    }

    @Test
    public void testSaveKuraChainsWithAdditionalRules() throws KuraException, IOException {
        setUpMock();

        Set<String> additionalFilterRules = new LinkedHashSet<>();
        additionalFilterRules.add("-A input-kura -p tcp --dport 8080 -j ACCEPT");
        additionalFilterRules.add("-A input-kura -p tcp --dport 9090 -j ACCEPT");

        Set<String> additionalNatRules = new LinkedHashSet<>();
        additionalNatRules.add("-A postrouting-kura -o eth2 -j MASQUERADE");

        Set<String> additionalMangleRules = new LinkedHashSet<>();
        additionalMangleRules.add("-A prerouting-kura -p tcp --dport 80 -j MARK --set-mark 1");

        IptablesConfig config = new IsolatedIptablesConfig(executorServiceMock);
        config.setAdditionalFilterRules(additionalFilterRules);
        config.setAdditionalNatRules(additionalNatRules);
        config.setAdditionalMangleRules(additionalMangleRules);

        config.saveKuraChains();

        // Verify additional rules are written to the configuration
        File tempFile = new File(config.getFirewallConfigFileName());
        assertTrue(tempFile.isFile());
        {
            try (Stream<String> lines = Files.lines(tempFile.toPath())) {
                AtomicBoolean foundFilterRule = new AtomicBoolean(false);
                AtomicBoolean foundNatRule = new AtomicBoolean(false);
                AtomicBoolean foundMangleRule = new AtomicBoolean(false);

                lines.forEach(line -> {
                    if (line.contains("-A input-kura -p tcp --dport 8080 -j ACCEPT")) {
                        foundFilterRule.set(true);
                    }
                    if (line.contains("-A postrouting-kura -o eth2 -j MASQUERADE")) {
                        foundNatRule.set(true);
                    }
                    if (line.contains("-A prerouting-kura -p tcp --dport 80 -j MARK --set-mark 1")) {
                        foundMangleRule.set(true);
                    }
                });

                assertTrue(foundFilterRule.get(), "Additional filter rule should be present");
                assertTrue(foundNatRule.get(), "Additional NAT rule should be present");
                assertTrue(foundMangleRule.get(), "Additional mangle rule should be present");
            }
            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testSaveKuraChainsWithDisallowedIcmp() throws KuraException, IOException {
        setUpMock();
        IptablesConfig config = new IsolatedIptablesConfig(executorServiceMock);
        config.setAllowIcmp(false);

        config.saveKuraChains();

        // Preserve this fork's explicit IPv4 echo request/reply DROP rules.
        File tempFile = new File(config.getFirewallConfigFileName());
        assertTrue(tempFile.isFile());
        {
            try (Stream<String> lines = Files.lines(tempFile.toPath())) {
                java.util.List<String> rules = lines.filter(line -> line.contains("-p icmp")).toList();
                assertEquals(2, rules.size());
                assertTrue(rules.stream().allMatch(line -> line.endsWith("-j DROP")));
                assertTrue(rules.stream().anyMatch(line -> line.contains("--icmp-type 8")));
                assertTrue(rules.stream().anyMatch(line -> line.contains("--icmp-type 0")));
            }
            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testRestoreWithInvalidFileContent() throws KuraException, IOException {
        IptablesConfig config = new IsolatedIptablesConfig() {
            @Override
            public String getFirewallConfigFileName() {
                return getFirewallConfigTmpFileName();
            }
        };

        // Create a file with invalid iptables content
        String invalidContent =
                "*filter\n" + ":INPUT DROP [0:0]\n" + "-A invalid-chain-name-that-causes-parsing-error\n" + "COMMIT\n";

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(config.getFirewallConfigTmpFileName()))) {
            writer.write(invalidContent);
        }

        try {
            // The restore method should not throw an exception for invalid content
            // It should just silently fail to parse invalid rules
            config.restore();

            // Verify that no valid rules were parsed from the invalid content
            assertTrue(config.getLocalRules().isEmpty(), "Local rules should be empty after parsing invalid content");
            assertTrue(config.getPortForwardRules().isEmpty(), "Port forward rules should be empty after parsing invalid content");
            assertTrue(config.getNatRules().isEmpty(), "NAT rules should be empty after parsing invalid content");
            assertTrue(config.getAutoNatRules().isEmpty(), "Auto NAT rules should be empty after parsing invalid content");
        } finally {
            File tempFile = new File(config.getFirewallConfigTmpFileName());
            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testGetIptablesCommand() {
        IptablesConfig config = new IsolatedIptablesConfig();
        String command = config.getIptablesCommand();

        assertNotNull(command, "iptables command should not be null");
        assertTrue(command.contains("iptables"), "iptables command should contain 'iptables'");
    }

    @Test
    public void testProtectedMethods() {
        IptablesConfig config = new IsolatedIptablesConfig() {
            // Override to make protected methods accessible for testing
            @Override
            protected String getIptablesCommand() {
                return super.getIptablesCommand();
            }

            @Override
            protected String[] getAllowIcmp() {
                return super.getAllowIcmp();
            }

            @Override
            protected String[] getNotAllowIcmp() {
                return super.getNotAllowIcmp();
            }
        };

        assertNotNull(config.getIptablesCommand(), "getIptablesCommand should not return null");
        assertNotNull(config.getAllowIcmp(), "getAllowIcmp should not return null");
        assertNotNull(config.getNotAllowIcmp(), "getNotAllowIcmp should not return null");

        assertTrue(config.getAllowIcmp().length > 0, "getAllowIcmp should return non-empty array");
        // Local IPv4 policy retains explicit echo request/reply DROP rules.
        assertEquals(2, config.getNotAllowIcmp().length, "This fork keeps explicit IPv4 ICMP DROP rules");
    }

    @Test
    public void testSaveKuraChainsFileMoving() throws KuraException, IOException {
        setUpMock();

        // Create a temporary config that we can control file paths for
        IptablesConfig config = new IsolatedIptablesConfig(executorServiceMock) {
            private String tempFileName =
                    directory.resolve("move.tmp").toString();
            private String configFileName =
                    directory.resolve("move.conf").toString();

            @Override
            public String getFirewallConfigTmpFileName() {
                return tempFileName;
            }

            @Override
            public String getFirewallConfigFileName() {
                return configFileName;
            }
        };

        config.saveKuraChains();

        // Verify the final config file was created (temp file was moved)
        File finalConfigFile = new File(config.getFirewallConfigFileName());
        assertTrue(finalConfigFile.exists(), "Final config file should exist");

        // Verify temp file was moved (no longer exists)
        File tempFile = new File(config.getFirewallConfigTmpFileName());
        assertFalse(tempFile.exists(), "Temp file should not exist after move");

        // Clean up
        Files.deleteIfExists(finalConfigFile.toPath());
    }

    @Test
    public void clearAllKuraChainsFailureTest() {
        setUpMock();

        // Create failure status to simulate command execution failure
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));

        // Mock any command execution to return failure status
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Test that clearAllKuraChains method executes and triggers error logging
        IptablesConfig iptablesConfigWithMock = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfigWithMock.clearAllKuraChains();

        // Verify that execute was called multiple times (once for each flush command)
        verify(executorServiceMock, atLeast(7)).execute(any(Command.class));
    }

    @Test
    public void saveFailureTest() {
        setUpMock();

        // Create failure status to simulate iptables-save command failure
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));

        // Mock save command to return failure
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Test that save method executes and triggers error logging
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.save();

        // Verify that execute was called for the save command
        verify(executorServiceMock, times(1)).execute(any(Command.class));
    }

    @Test
    public void saveWithFilenameFailureTest() {
        setUpMock();

        // Create failure status to simulate iptables-save command failure
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));

        // Mock save command to return failure
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Test that save method with filename executes and triggers error logging
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.save(directory.resolve("test-iptables").toString());

        // Verify that execute was called for the save command
        verify(executorServiceMock, times(1)).execute(any(Command.class));
    }

    @Test
    public void restoreFailureTest() throws IOException {
        setUpMock();

        // Create failure status to simulate iptables-restore command failure
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));

        // Mock restore command to return failure
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Create a temporary file for the test
        File tempFile = Files.createTempFile(directory, "test-iptables", ".tmp").toFile();


        // Test that restore method executes and triggers error logging
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.restore(tempFile.getAbsolutePath());

        // Verify that execute was called for the restore command
        verify(executorServiceMock, times(1)).execute(any(Command.class));
    }

    @Test
    public void restoreFileDeleteFailureTest() throws IOException {
        setUpMock();

        // Create success status for the restore command
        CommandStatus successStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));

        // Mock restore command to return success
        when(executorServiceMock.execute(any(Command.class))).thenReturn(successStatus);

        // Use a non-existent directory path to trigger file deletion IOException
        String invalidPath = directory.resolve("missing/test-file").toString();

        // Test that restore method executes and triggers file deletion error logging
        // (line 389)
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        iptablesConfig.restore(invalidPath);

        // Verify that execute was called for the restore command
        verify(executorServiceMock, times(1)).execute(any(Command.class));
    }

    @Test
    public void applyRulesWithLocalRulesFailureTest() {
        setUpMock();

        // Create failure status for any command execution
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Create IptablesConfig with local rules
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        Set<LocalRule> localRules = new HashSet<>();
        localRules.add(new LocalRule(0, null, null, null, null, null, null));
        iptablesConfig.setLocalRules(localRules);

        // This will call writeLocalRulesToFilterTable(null) which triggers command
        // execution
        iptablesConfig.applyRules();

        // Verify that commands were executed
        verify(executorServiceMock, atLeast(1)).execute(any(Command.class));
    }

    @Test
    public void applyRulesWithNatRulesFailureTest() {
        setUpMock();

        // Create failure status for any command execution
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Create IptablesConfig with NAT rules
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        Set<NATRule> natRules = new HashSet<>();
        try {
            NATRule natRule =
                    new NATRule("eth0", "eth1", "tcp", "192.168.1.0/24", "0.0.0.0/0", true, RuleType.IP_FORWARDING);
            natRules.add(natRule);
            iptablesConfig.setNatRules(natRules);
        } catch (Exception e) {
            throw new AssertionError("Cannot build NAT fixture", e);
        }

        // This will call writeNatRulesToFilterTable(null) which triggers command
        // execution
        iptablesConfig.applyRules();

        // Verify that commands were executed
        verify(executorServiceMock, atLeast(1)).execute(any(Command.class));
    }

    @Test
    public void applyRulesWithAutoNatRulesFailureTest() {
        setUpMock();

        // Create failure status for any command execution
        CommandStatus failureStatus = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));
        when(executorServiceMock.execute(any(Command.class))).thenReturn(failureStatus);

        // Create IptablesConfig with auto NAT rules
        IptablesConfig iptablesConfig = new IsolatedIptablesConfig(executorServiceMock);
        Set<NATRule> autoNatRules = new HashSet<>();
        try {
            NATRule autoNatRule = new NATRule("eth0", "eth1", true, RuleType.GENERIC);
            autoNatRules.add(autoNatRule);
            iptablesConfig.setAutoNatRules(autoNatRules);
        } catch (Exception e) {
            throw new AssertionError("Cannot build NAT fixture", e);
        }

        // This will call writeAutoNatRulesToFilterTable(null) which triggers command
        // execution
        iptablesConfig.applyRules();

        // Verify that commands were executed
        verify(executorServiceMock, atLeast(1)).execute(any(Command.class));
    }

    // Tests merged from IptablesConfigCoverageTest to consolidate test coverage

    private class IptablesConfigWithBadTmpPath extends IsolatedIptablesConfig {
        IptablesConfigWithBadTmpPath() {
            super();
        }

        @Override
        public String getFirewallConfigTmpFileName() {
            // Point to a special file path that is not a directory to provoke IOException
            // when trying to create a file inside it.
            return directory.resolve("missing/iptables-kura.tmp").toString();
        }
    }

    @Test
    public void saveKuraChains_shouldThrowKuraIOException_onFileCreationFailure() {
        IptablesConfig cfg = new IptablesConfigWithBadTmpPath();
        try {
            cfg.saveKuraChains();
            fail("Expected KuraIOException to be thrown");
        } catch (KuraIOException e) {
            // Expected exception - test passes
        } catch (KuraException e) {
            // Check if it's actually a KuraIOException wrapped
            if (!(e instanceof KuraIOException)) {
                fail("Expected KuraIOException, but got: " + e.getClass().getSimpleName());
            }
        }
    }

    @Test
    public void clearAllKuraChainsExecutesFlushCommands() throws KuraException {
        setUpMock();
        IptablesConfig cfg = new IsolatedIptablesConfig(executorServiceMock);
        cfg.clearAllKuraChains();

        // Verify that execute was called multiple times (at least once for each flush
        // command)
        verify(executorServiceMock, atLeast(7)).execute(any(Command.class));
    }

    @Test
    public void restore_shouldCatchIOException_onDeleteIfExistsFailure() throws Exception {
        setUpMock();

        // Prepare a non-empty temporary directory so Files.deleteIfExists throws
        // DirectoryNotEmptyException
        File tempDir = Files.createDirectory(directory.resolve("nonempty")).toFile();
        // Turn it into a directory: delete the file and create a directory with the
        // same name
        File inner = new File(tempDir, "inner.txt");
        try (FileWriter fw = new FileWriter(inner)) {
            fw.write("data");
        }

        IptablesConfig cfg = new IsolatedIptablesConfig(executorServiceMock);
        // Stub restore command success explicitly to be safe
        Command cmd = new Command(new String[] {"iptables-restore", tempDir.getAbsolutePath()});
        cmd.setExecuteInAShell(true);
        CommandStatus ok = new CommandStatus(cmd, new LinuxExitStatus(0));
        org.mockito.Mockito.when(executorServiceMock.execute(cmd)).thenReturn(ok);

        // Should not throw; deletion fails inside finally and is caught (line 389)
        cfg.restore(tempDir.getAbsolutePath());

        // Cleanup: remove inner file then directory
        inner.delete();
        tempDir.delete();
    }
}
