<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2026 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>kura-networking.parent</artifactId>
        <version>3.0.0-SNAPSHOT</version>
        <relativePath>../bundles/pom.xml</relativePath>
    </parent>

    <artifactId>kura-firewall-only.distrib</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.net</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.net.admin.firewall</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.net</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.net.configuration</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <properties>
        <addon.5s.installation.dir>/opt/eclipse/kura/siblings/firewall/5s</addon.5s.installation.dir>
        <addon.4s.installation.dir>/opt/eclipse/kura/siblings/firewall/4s</addon.4s.installation.dir>
        <addon.4.installation.dir>/opt/eclipse/kura/siblings/firewall/4</addon.4.installation.dir>

        <org.eclipse.kura.linux.net.name>org.eclipse.kura.linux.net</org.eclipse.kura.linux.net.name>
        <org.eclipse.kura.net.admin.firewall.name>org.eclipse.kura.net.admin.firewall</org.eclipse.kura.net.admin.firewall.name>
        <org.eclipse.kura.core.net.name>org.eclipse.kura.core.net</org.eclipse.kura.core.net.name>
        <org.eclipse.kura.net.configuration.name>org.eclipse.kura.net.configuration</org.eclipse.kura.net.configuration.name>

        <deb.architecture>all</deb.architecture>
        <package.name>kura-firewall-only</package.name>
        <summary>Eclipse Kura Firewall add-on</summary>
        <long.description>The Kura Firewall add-on provides firewall management without taking over host network configuration.</long.description>
    </properties>

    <profiles>
        <profile>
            <id>debugBuild</id>
            <activation>
                <property>
                    <name>!releaseBuild</name>
                </property>
            </activation>
            <properties>
                <maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
                <package.snapshot>git${maven.build.timestamp}.${git.commit.id.abbrev}</package.snapshot>
                <package.version>${release.version}~${package.snapshot}</package.version>
                <package.revision>1</package.revision>
            </properties>
        </profile>
        <profile>
            <id>releaseBuild</id>
            <activation>
                <property>
                    <name>releaseBuild</name>
                </property>
            </activation>
            <properties>
                <package.version>${release.version}</package.version>
                <package.revision>1</package.revision>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>regex-property</id>
                        <goals>
                            <goal>regex-property</goal>
                        </goals>
                        <configuration>
                            <name>release.version</name>
                            <value>${project.version}</value>
                            <regex>-SNAPSHOT</regex>
                            <replacement></replacement>
                            <failIfNoMatch>false</failIfNoMatch>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
                <version>9.0.1</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <injectAllReactorProjects>true</injectAllReactorProjects>
                    <generateGitPropertiesFile>false</generateGitPropertiesFile>
                    <skipPoms>false</skipPoms>
                    <includeOnlyProperties>
                        <includeOnlyProperty>^git.commit.id.abbrev$</includeOnlyProperty>
                    </includeOnlyProperties>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-bundles-to-distrib</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <excludeTypes>pom</excludeTypes>
                            <excludeClassifiers>sources</excludeClassifiers>
                            <excludeTransitive>true</excludeTransitive>
                            <outputDirectory>${project.build.directory}/plugins</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
                <version>1.12</version>
                <executions>
                    <execution>
                        <id>generate-deb</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <deb>${basedir}/target/deb/${package.name}-${package.version}-${package.revision}_${deb.architecture}.deb</deb>
                            <snapshotExpand>true</snapshotExpand>
                            <snapshotTemplate>${package.snapshot}</snapshotTemplate>
                            <controlDir>${project.basedir}/deb/control</controlDir>
                            <skipPOMs>false</skipPOMs>
                            <dataSet>
                                <data>
                                    <src>${basedir}/target/plugins/${org.eclipse.kura.linux.net.name}-${project.version}.jar</src>
                                    <dst>${org.eclipse.kura.linux.net.name}-${project.version}.jar</dst>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>${addon.4.installation.dir}</prefix>
                                        <user>kurad</user>
                                        <group>kurad</group>
                                        <filemode>600</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <src>${basedir}/target/plugins/${org.eclipse.kura.core.net.name}-${project.version}.jar</src>
                                    <dst>${org.eclipse.kura.core.net.name}-${project.version}.jar</dst>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>${addon.4s.installation.dir}</prefix>
                                        <user>kurad</user>
                                        <group>kurad</group>
                                        <filemode>600</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <src>${basedir}/target/plugins/${org.eclipse.kura.net.configuration.name}-${project.version}.jar</src>
                                    <dst>${org.eclipse.kura.net.configuration.name}-${project.version}.jar</dst>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>${addon.4s.installation.dir}</prefix>
                                        <user>kurad</user>
                                        <group>kurad</group>
                                        <filemode>600</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <src>${basedir}/target/plugins/${org.eclipse.kura.net.admin.firewall.name}-${project.version}.jar</src>
                                    <dst>${org.eclipse.kura.net.admin.firewall.name}-${project.version}.jar</dst>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>${addon.5s.installation.dir}</prefix>
                                        <user>kurad</user>
                                        <group>kurad</group>
                                        <filemode>600</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <type>file</type>
                                    <src>${project.basedir}/src/main/resources/scripts/customize_firewall_snapshot.py</src>
                                    <dst>customize_firewall_snapshot.py</dst>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/opt/eclipse/kura/kura-firewall-install</prefix>
                                        <user>root</user>
                                        <group>root</group>
                                        <filemode>644</filemode>
                                    </mapper>
                                </data>
                                <data>
                                    <type>files</type>
                                    <paths>
                                        <path>${project.basedir}/src/main/resources/scripts/firewall.service</path>
                                    </paths>
                                    <dst>/lib/systemd/system/</dst>
                                </data>
                                <data>
                                    <src>${project.basedir}/src/main/resources/scripts/firewall-only.init</src>
                                    <dst>firewall</dst>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/opt/eclipse/kura/bin</prefix>
                                        <user>root</user>
                                        <group>root</group>
                                        <filemode>700</filemode>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
