<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2023, 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.eclipse.kura</groupId>
    <artifactId>kura-networking.parent</artifactId>
    <version>3.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>org.eclipse.kura.nm</artifactId>
  <version>2.0.0-SNAPSHOT</version>
  <packaging>bundle</packaging>
  <dependencies>
    <dependency>
      <groupId>com.github.hypfvieh</groupId>
      <artifactId>dbus-java-core</artifactId>
      <version>5.2.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.hypfvieh</groupId>
      <artifactId>dbus-java-transport-jnr-unixsocket</artifactId>
      <version>5.2.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jffi</artifactId>
      <version>1.3.15</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jffi</artifactId>
      <version>1.3.15</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
      <classifier>native</classifier>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-a64asm</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-constants</artifactId>
      <version>0.10.4</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-enxio</artifactId>
      <version>0.32.20</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-ffi</artifactId>
      <version>2.2.19</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-posix</artifactId>
      <version>3.1.22</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-unixsocket</artifactId>
      <version>0.38.24</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-x86asm</artifactId>
      <version>1.0.2</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.21.0</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>4.0.2</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.20.0</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk18on</artifactId>
      <version>1.86</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk18on</artifactId>
      <version>1.86</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.api</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.core.configuration</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.core.keystore</artifactId>
      <version>2.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.core.net</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.core</artifactId>
      <version>2.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.linux.net</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.linux.position.spi</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.net.configuration</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.kura</groupId>
      <artifactId>org.eclipse.kura.util</artifactId>
      <version>2.0.0-SNAPSHOT</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.eclipse.platform</groupId>
      <artifactId>org.eclipse.osgi</artifactId>
      <version>3.24.100</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.component</artifactId>
      <version>1.5.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.event</artifactId>
      <version>1.4.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.useradmin</artifactId>
      <version>1.1.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.util.measurement</artifactId>
      <version>1.0.2</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.util.position</artifactId>
      <version>1.0.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-analysis</artifactId>
      <version>9.7.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-commons</artifactId>
      <version>9.7.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-tree</artifactId>
      <version>9.7.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm-util</artifactId>
      <version>9.7.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>9.7.1</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.18</version>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.component.annotations</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>kura-test-support</artifactId><version>6.0.0-SNAPSHOT</version><scope>test</scope></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
    <dependency><groupId>org.mockito</groupId><artifactId>mockito-junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
  <properties>
    <kura.basedir>${project.basedir}/..</kura.basedir>
    <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/../test/org.eclipse.kura.nm.test/target/site/jacoco-aggregate/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
  </properties>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>src/main/java</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>${project.basedir}</directory>
        <includes>
          <include>META-INF/**</include>
          <include>OSGI-INF/**</include>
          <include>about.html</include>
          <include>about_files/**</include>
          <include>lib/dbus-java-core.jar</include>
          <include>lib/dbus-java-transport-jnr-unixsocket.jar</include>
          <include>lib/jffi.jar</include>
          <include>lib/jffi-native.jar</include>
          <include>lib/jnr-a64asm.jar</include>
          <include>lib/jnr-constants.jar</include>
          <include>lib/jnr-enxio.jar</include>
          <include>lib/jnr-ffi.jar</include>
          <include>lib/jnr-posix.jar</include>
          <include>lib/jnr-unixsocket.jar</include>
          <include>lib/jnr-x86asm.jar</include>
        </includes>
        <excludes>
          <exclude>META-INF/MANIFEST.MF</exclude>
          <exclude>lib/**/*.jar</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions><execution><id>prepare-handwritten-manifest</id><phase>generate-resources</phase></execution>
          <execution>
            <id>copy-generated-condition-descriptor</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <copy file="${project.build.directory}/generated-ds/OSGI-INF/ModemManagerPositionProvider.xml" tofile="${project.build.outputDirectory}/OSGI-INF/ModemManagerPositionProvider.xml" overwrite="true" />
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-private-embedded-jars</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.github.hypfvieh</groupId>
                  <artifactId>dbus-java-core</artifactId>
                  <version>5.2.0</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>dbus-java-core.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.hypfvieh</groupId>
                  <artifactId>dbus-java-transport-jnr-unixsocket</artifactId>
                  <version>5.2.0</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>dbus-java-transport-jnr-unixsocket.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jffi</artifactId>
                  <version>1.3.15</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jffi.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jffi</artifactId>
                  <version>1.3.15</version>
                  <classifier>native</classifier>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jffi-native.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-a64asm</artifactId>
                  <version>1.0.0</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-a64asm.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-constants</artifactId>
                  <version>0.10.4</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-constants.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-enxio</artifactId>
                  <version>0.32.20</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-enxio.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-ffi</artifactId>
                  <version>2.2.19</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-ffi.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-posix</artifactId>
                  <version>3.1.22</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-posix.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-unixsocket</artifactId>
                  <version>0.38.24</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-unixsocket.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-x86asm</artifactId>
                  <version>1.0.2</version>
                  <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                  <destFileName>jnr-x86asm.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.hypfvieh</groupId>
                  <artifactId>dbus-java-core</artifactId>
                  <version>5.2.0</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>dbus-java-core.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.hypfvieh</groupId>
                  <artifactId>dbus-java-transport-jnr-unixsocket</artifactId>
                  <version>5.2.0</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>dbus-java-transport-jnr-unixsocket.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jffi</artifactId>
                  <version>1.3.15</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jffi.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jffi</artifactId>
                  <version>1.3.15</version>
                  <classifier>native</classifier>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jffi-native.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-a64asm</artifactId>
                  <version>1.0.0</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-a64asm.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-constants</artifactId>
                  <version>0.10.4</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-constants.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-enxio</artifactId>
                  <version>0.32.20</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-enxio.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-ffi</artifactId>
                  <version>2.2.19</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-ffi.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-posix</artifactId>
                  <version>3.1.22</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-posix.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-unixsocket</artifactId>
                  <version>0.38.24</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-unixsocket.jar</destFileName>
                </artifactItem>
                <artifactItem>
                  <groupId>com.github.jnr</groupId>
                  <artifactId>jnr-x86asm</artifactId>
                  <version>1.0.2</version>
                  <outputDirectory>${project.build.outputDirectory}/lib</outputDirectory>
                  <destFileName>jnr-x86asm.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <_dsannotations>!*</_dsannotations>
            <_bundleannotations>!*</_bundleannotations>
            <_dsannotations-options>nocapabilities,norequirements</_dsannotations-options>
            <_include>${project.build.directory}/osgi/MANIFEST.MF</_include>
            <_nodefaultversion>true</_nodefaultversion>
            <_removeheaders>Include-Resource,Private-Package</_removeheaders>
            <Private-Package>!*</Private-Package>
            <Include-Resource>${project.build.outputDirectory}</Include-Resource>
            <Export-Package>!*</Export-Package>
          </instructions>
        </configuration>
        <executions>
          <execution>
            <id>generate-existing-condition-descriptor</id>
            <phase>process-classes</phase>
            <goals>
              <goal>manifest</goal>
            </goals>
            <configuration>
              <exportScr>true</exportScr>
              <scrLocation>${project.build.directory}/generated-ds</scrLocation>
              <manifestLocation>${project.build.directory}/osgi/ds-generation</manifestLocation>
              <instructions>
                <_dsannotations>org.eclipse.kura.nm.position.MMPositionProvider</_dsannotations>
              </instructions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
