#!/bin/bash
#
# Copyright (c) 2023, 2025 Eurotech and/or its affiliates and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#  Eurotech
#

XML_HEADER='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
SNAPSHOT_0_PATH='/opt/eclipse/kura/user/snapshots/snapshot_0.xml'

check_snapshot_0() {
    if [[ -f "$SNAPSHOT_0_PATH" ]]; then
      read -r line < "$SNAPSHOT_0_PATH"
      if [[ "$line" != "$XML_HEADER"* ]]; then
        echo "Error: Snapshot encrypted." >&2
        echo "In order to install kura-networking, kura-core must never have been started." >&2
        exit 1
      fi
    fi
}


case "$1" in
    configure)
        STATUS=install
        ;;
        
    abort-remove)
        echo "Uninstallation failed."
        exit 1
        ;;

    abort-upgrade)
        echo "Upgrade failed."
        exit 1
        ;;
        
    *)
        echo "postinst scripts called with unknown parameter $1"
        exit 1
        ;;
esac

echo "Checking kura snapshot_0.xml..."
check_snapshot_0
echo "kura snapshot_0.xml ok."

echo "Installing Kura networking..."
export TIMESTAMP=`date +%Y%m%d%H%M`
export LOG=/var/log/kura_network_install_${TIMESTAMP}.log
export PATH=$PATH:/usr/java/bin:/usr/bin/java/bin
echo "Configuring Kura networking..."

bash /opt/eclipse/kura/.data/kura_network_install.sh ${STATUS} /opt/eclipse kura 2>&1 | tee -a $LOG | systemd-cat -t Kura

if test -f /tmp/install_error; then
    echo "Kura networking installation failed. Please uninstall Kura networking manually."
    rm /tmp/install_error
    exit 1
fi

echo "Kura networking installation completed."