#!/bin/bash
#
#  Copyright (c) 2020, 2025 Eurotech and/or its affiliates and others
#
#  This program and the accompanying materials are made
#  available under the terms of the Eclipse Public License 2.0
#  which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#   Eurotech
#
# Content with portions generated by generative AI platform

function create_polkit_rules {

    # get polkit package version without using apt's interactive CLI
    POLKIT_VERSION=$(dpkg-query -W -f='${Version}' 'libpolkit*' 2>/dev/null | head -n 1)
    if [ -z "${POLKIT_VERSION}" ]; then
        POLKIT_VERSION=0
    fi

    # add polkit policy
    if [[ ${POLKIT_VERSION} < 0.106 ]]; then
        if [ ! -f /etc/polkit-1/localauthority/50-local.d/51-org.freedesktop.systemd1.pkla ]; then
            echo "[No password prompt for kurad user]
Identity=unix-user:kurad
Action=org.freedesktop.systemd1.*
ResultInactive=no
ResultActive=no
ResultAny=yes" >/etc/polkit-1/localauthority/50-local.d/51-org.freedesktop.systemd1.pkla
        fi

        if [ ! -f /etc/polkit-1/localauthority/50-local.d/52-org.freedesktop.networkmanager.pkla ]; then
            echo "[No password prompt for kurad user when using NetworkManager]
Identity=unix-user:kurad
Action=org.freedesktop.NetworkManager.*
ResultInactive=no
ResultActive=no
ResultAny=yes" >/etc/polkit-1/localauthority/50-local.d/52-org.freedesktop.networkmanager.pkla
        fi
        if [ ! -f /etc/polkit-1/localauthority/50-local.d/53-org.freedesktop.modemmanager.pkla ]; then
            echo "[No password prompt for kurad user when using ModemManager]
Identity=unix-user:kurad
Action=org.freedesktop.ModemManager1.*
ResultInactive=no
ResultActive=no
ResultAny=yes" >/etc/polkit-1/localauthority/50-local.d/53-org.freedesktop.modemmanager.pkla
        fi
        if [ ! -f /etc/polkit-1/localauthority/50-local.d/54-fi.w1.wpa_supplicant1.pkla ]; then
            echo "[No password prompt for kurad user when using Wpa Supplicant]
Identity=unix-user:kurad
Action=fi.w1.wpa_supplicant1.*
ResultInactive=no
ResultActive=no
ResultAny=yes" >/etc/polkit-1/localauthority/50-local.d/54-fi.w1.wpa_supplicant1.pkla
        fi
    else
        if [ ! -f /usr/share/polkit-1/rules.d/kura.rules ]; then
            echo "polkit.addRule(function(action, subject) {
    if (action.id == \"org.freedesktop.systemd1.manage-units\" &&
        subject.user == \"kurad\" &&
        (action.lookup(\"unit\") == \"named.service\" ||
        action.lookup(\"unit\") == \"chrony.service\" ||
        action.lookup(\"unit\") == \"chronyd.service\" ||
        action.lookup(\"unit\") == \"bluetooth.service\")) {
        return polkit.Result.YES;
    }
    if (action.id == \"org.freedesktop.systemd1.manage-unit-files\" &&
        subject.user == \"kurad\") {
        return polkit.Result.YES;
    }
    if ((action.id == \"org.freedesktop.login1.reboot-multiple-sessions\" ||
        action.id == \"org.freedesktop.login1.suspend-multiple-sessions\" ||
        action.id == \"org.freedesktop.login1.power-off-multiple-sessions\") &&
        subject.user == \"kurad\") {
        return polkit.Result.YES;
    }
});" >/usr/share/polkit-1/rules.d/kura.rules
        fi
        if [ ! -f /usr/share/polkit-1/rules.d/kura-nm.rules ]; then
            echo "polkit.addRule(function(action, subject) {
    if ((action.id.indexOf(\"org.freedesktop.NetworkManager.\") == 0 ||
        action.id.indexOf(\"org.freedesktop.ModemManager1.\") == 0 ||
        action.id.indexOf(\"fi.w1.wpa_supplicant1.\") == 0) &&
        subject.user == \"kurad\") {
        return polkit.Result.YES;
    }
});" >/usr/share/polkit-1/rules.d/kura-nm.rules
        fi
    fi

    # modify pam policy
    if [ -f /etc/pam.d/su ]; then
        sed -i '/^auth       sufficient pam_rootok.so/a auth       [success=ignore default=1] pam_succeed_if.so user = kura\nauth       sufficient                 pam_succeed_if.so use_uid user = kurad' /etc/pam.d/su
    fi

    # grant kurad user the privileges to manage ble via dbus
    BLUETOOTH_DBUS_POLKIT_CONFIG="/etc/dbus-1/system.d/bluetooth.conf"
    if [ ! -f "${BLUETOOTH_DBUS_POLKIT_CONFIG}" ] && [ -f /usr/share/dbus-1/system.d/bluetooth.conf ]; then
        BLUETOOTH_DBUS_POLKIT_CONFIG=/usr/share/dbus-1/system.d/bluetooth.conf
    fi
    if [ -f "${BLUETOOTH_DBUS_POLKIT_CONFIG}" ] && ! grep -q kurad "${BLUETOOTH_DBUS_POLKIT_CONFIG}"; then
        echo "Patching '$BLUETOOTH_DBUS_POLKIT_CONFIG' to grant kurad user the privileges to manage bluetooth via dbus"

        cp "$BLUETOOTH_DBUS_POLKIT_CONFIG" "$BLUETOOTH_DBUS_POLKIT_CONFIG".kurasave
        awk 'done != 1 && /^<\/busconfig>/ {
            print "  <policy user=\"kurad\">"
            print "    <allow own=\"org.bluez\"/>"
            print "    <allow send_destination=\"org.bluez\"/>"
            print "    <allow send_interface=\"org.bluez.Agent1\"/>"
            print "    <allow send_interface=\"org.bluez.MediaEndpoint1\"/>"
            print "    <allow send_interface=\"org.bluez.MediaPlayer1\"/>"
            print "    <allow send_interface=\"org.bluez.Profile1\"/>"
            print "    <allow send_interface=\"org.bluez.GattCharacteristic1\"/>"
            print "    <allow send_interface=\"org.bluez.GattDescriptor1\"/>"
            print "    <allow send_interface=\"org.bluez.LEAdvertisement1\"/>"
            print "    <allow send_interface=\"org.freedesktop.DBus.ObjectManager\"/>"
            print "    <allow send_interface=\"org.freedesktop.DBus.Properties\"/>"
            print "  </policy>\n"
            done = 1
        } 1' "$BLUETOOTH_DBUS_POLKIT_CONFIG" >tempfile && mv tempfile "$BLUETOOTH_DBUS_POLKIT_CONFIG"
    fi

    # grant kurad user the privileges to manage wpa supplicant via dbus
    WPASUPP_DBUS_POLKIT_CONFIG="/etc/dbus-1/system.d/wpa_supplicant.conf"
    if [ ! -f "${WPASUPP_DBUS_POLKIT_CONFIG}" ] && [ -f /usr/share/dbus-1/system.d/wpa_supplicant.conf ]; then
        WPASUPP_DBUS_POLKIT_CONFIG=/usr/share/dbus-1/system.d/wpa_supplicant.conf
    fi
    if [ -f "$WPASUPP_DBUS_POLKIT_CONFIG" ] && ! grep -q kurad "$WPASUPP_DBUS_POLKIT_CONFIG"; then
        echo "Patching '$WPASUPP_DBUS_POLKIT_CONFIG' to grant kurad user the privileges to manage wpa supplicant via dbus"

        cp "$WPASUPP_DBUS_POLKIT_CONFIG" "$WPASUPP_DBUS_POLKIT_CONFIG".kurasave
        awk 'done != 1 && /^<\/busconfig>/ {
            print "    <policy user=\"kurad\">"
            print "        <allow own=\"fi.w1.wpa_supplicant1\"/>"
            print "        <allow send_destination=\"fi.w1.wpa_supplicant1\"/>"
            print "        <allow send_interface=\"fi.w1.wpa_supplicant1\"/>"
            print "        <allow receive_sender=\"fi.w1.wpa_supplicant1\" receive_type=\"signal\"/>"
            print "    </policy>\n"
            done = 1
        } 1' "$WPASUPP_DBUS_POLKIT_CONFIG" >tempfile && mv tempfile "$WPASUPP_DBUS_POLKIT_CONFIG"
    fi
}

function delete_polkit_rules {

    # remove polkit policy
    if [ -f /usr/share/polkit-1/rules.d/kura.rules ]; then
        rm -f /usr/share/polkit-1/rules.d/kura.rules
    fi
    if [ -f /etc/polkit-1/localauthority/50-local.d/51-org.freedesktop.systemd1.pkla ]; then
        rm -f /etc/polkit-1/localauthority/50-local.d/51-org.freedesktop.systemd1.pkla
    fi
    if [ -f /etc/polkit-1/localauthority/50-local.d/52-org.freedesktop.networkmanager.pkla ]; then
        rm -f /etc/polkit-1/localauthority/50-local.d/52-org.freedesktop.networkmanager.pkla
    fi
    if [ -f /etc/polkit-1/localauthority/50-local.d/53-org.freedesktop.modemmanager.pkla ]; then
        rm -f /etc/polkit-1/localauthority/50-local.d/53-org.freedesktop.modemmanager.pkla
    fi
    if [ -f /etc/polkit-1/localauthority/50-local.d/54-fi.w1.wpa_supplicant1.pkla ]; then
        rm -f /etc/polkit-1/localauthority/50-local.d/54-fi.w1.wpa_supplicant1.pkla
    fi

    # recover pam policy
    if [ -f /etc/pam.d/su ]; then
        sed -i '/^auth       sufficient pam_rootok.so/ {n;d}' /etc/pam.d/su
        sed -i '/^auth       sufficient pam_rootok.so/ {n;d}' /etc/pam.d/su
    fi

    # recover old configs
    BLUETOOTH_DBUS_POLKIT_CONFIG="/etc/dbus-1/system.d/bluetooth.conf"
    if [ ! -f "${BLUETOOTH_DBUS_POLKIT_CONFIG}.kurasave" ] && [ -f /usr/share/dbus-1/system.d/bluetooth.conf.kurasave ]; then
        BLUETOOTH_DBUS_POLKIT_CONFIG=/usr/share/dbus-1/system.d/bluetooth.conf
    fi
    if [ -f "${BLUETOOTH_DBUS_POLKIT_CONFIG}.kurasave" ]; then
        mv "${BLUETOOTH_DBUS_POLKIT_CONFIG}.kurasave" "${BLUETOOTH_DBUS_POLKIT_CONFIG}"
    fi
    WPASUPP_DBUS_POLKIT_CONFIG="/etc/dbus-1/system.d/wpa_supplicant.conf"
    if [ ! -f "${WPASUPP_DBUS_POLKIT_CONFIG}.kurasave" ] && [ -f /usr/share/dbus-1/system.d/wpa_supplicant.conf.kurasave ]; then
        WPASUPP_DBUS_POLKIT_CONFIG=/usr/share/dbus-1/system.d/wpa_supplicant.conf
    fi
    if [ -f "${WPASUPP_DBUS_POLKIT_CONFIG}.kurasave" ]; then
        mv "${WPASUPP_DBUS_POLKIT_CONFIG}.kurasave" "${WPASUPP_DBUS_POLKIT_CONFIG}"
    fi
}

INSTALL=YES

while [[ $# > 0 ]]; do
    key="$1"

    case $key in
    -i | --install)
        INSTALL=YES
        ;;
    -u | --uninstall)
        INSTALL=NO
        ;;
    -h | --help)
        echo
        echo "Options:"
        echo "    -i | --install    create kura default users"
        echo "    -u | --uninstall  delete kura default users"
        echo "Default: --install"
        exit 0
        ;;
    *)
        echo "Unknown option."
        exit 1
        ;;
    esac
    shift # past argument or value
done

if [[ $INSTALL == "YES" ]]; then
    create_polkit_rules
else
    delete_polkit_rules
fi
